### ISSUE TITLE
OA-Statistik funktioniert nicht

### ISSUE THREAD

**Issue by kadowa** [UB-Heidelberg/UBHD-OMPArthistoricum#1]
![statistik](https://cloud.githubusercontent.com/assets/8066366/12885380/cbd3775a-ce65-11e5-9772-ba393332a794.png)

**Comment by withanage** [comment]
ist noch nicht konfiguriert. sollte erstmal  konfiguriert werden.

**Comment by kadowa** [comment]
Davon bin ich ausgegangen; ist als Reminder gedacht, dass umzusetzen, wenn du wieder da bist.

**Comment by withanage** [comment]
implemented  and intergrated
