### ISSUE TITLE
Autoren werden beim Inhaltsverzeichnis nicht neben den einzelnen Beiträgen angezeigt

### ISSUE THREAD

**Issue by dastewo** [UB-Heidelberg/UBHD-OMPArthistoricum#2]
@kadowa @withanage 

Beim Aufruf eines Buchs wird zwar das Inhaltsverzeichnis mit allen PDFs angezeigt, nicht aber, welcher Autor welchen Teil geschrieben hat.

Viele Grüße
Daniela

**Comment by kadowa** [comment]
This issue was moved to UB-Heidelberg/UBHD-OMPPortal#7
